### ISSUE TITLE
Check attributesForFaceting with searchable

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-rails#231] opened 2017-05-02 09:12 UTC
A user is reporting issues using `attributesForFaceting` with the new `searchable` modifier for facets, while setting it in the dashboard worked fine.
I'm unsure why it didn't work, but setting up a reproduction rails app should be straightforward.

**Comment by redox** [comment] 2017-07-28 16:12
Closing it until reproduction case because I cannot see why it would fail.

**Closed by redox** 2017-07-28 16:12 UTC

**Comment by earksiinni** [comment] 2020-06-30 16:24
I had this exact same problem. Turns out that the client wasn't updating my facets due to a misconfigured setting elsewhere that was silently failing (see https://github.com/algolia/algoliasearch-rails/issues/383).
