### ISSUE TITLE
ActiveRecord_Relation#index is redefined by this gem

### ISSUE THREAD

**Issue by ybart** [algolia/algoliasearch-rails#108] opened 2016-04-22 14:18 UTC
Here is the offending code:

https://github.com/algolia/algoliasearch-rails/blob/1e4d8fb6eecd7d7a854058939055f405011ed1ee/lib/algoliasearch-rails.rb#L291

Here is sample code demonstrating the issue:

``` ruby
class Team < ActiveRecord::Base
  algolia_search ...
end
```

```
irb(main):001> Team.all.index(Team.first)
ArgumentError: Invalid index/slave name: #<Team:0x007fd17c10b5a8>
```

**Comment by redox** [comment] 2016-04-23 13:32
But it should only define the `index` method it is not already defined; isn't it?

**Comment by ybart** [comment] 2016-04-23 13:59
It seems there is some strange edge case. It might be because index is not defined for ActiveRecord::Base so method_defined? returns false. But defining index on ActiveRecord::Base subclass seems to override already existing index method for ActiveRecord_Relation.

**Comment by julienbourdeau** [comment] 2019-03-21 14:41
I cannot reproduce this issue anymore. I'm assuming this was fixed, probably on the Rails side.

```
irb(main):005:0> Contact.all.index(Contact.first)
  Contact Load (0.1ms)  SELECT  "contacts".* FROM "contacts" ORDER BY "contacts"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Contact Load (3.5ms)  SELECT "contacts".* FROM "contacts"
=> 0
irb(main):006:0> Contact.all.index(Contact.last)
  Contact Load (0.2ms)  SELECT  "contacts".* FROM "contacts" ORDER BY "contacts"."id" DESC LIMIT ?  [["LIMIT", 1]]
  Contact Load (2.9ms)  SELECT "contacts".* FROM "contacts"
=> 499
```

@ybart  I'm closing it but if you still have issue with this, please let me know here.

**Closed by julienbourdeau** 2019-03-21 14:41 UTC
Labels: help wanted
